# Non-working

FROM alpine:3.7

RUN apk add --update \
    python3 \
    python3-dev \
    build-base \
  && pip3 install virtualenv \
  && rm -rf /var/cache/apk/*

WORKDIR /app

COPY . /app
RUN pip3 install -r /app/project/requirements.txt
RUN python /app/project/db_create.py

EXPOSE 5000
CMD ["python", "/app/project/run.py"]